import './globals.css';

import Navbar from './components/navigation';
import Footer from './components/footer';

export const metadata = {
	title: 'Books by Sara',
	description: 'Generated by create next app',
	icons: {
		icon: '/icon.ico',
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<div className='container bg-white md:mx-auto my-5'>
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
