import { Inter } from 'next/font/google';
import './globals.css';

import Navbar from './components/navigation';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='container bg-white mx-auto my-5'>
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
